AllCops:
  Excludes:
    - node_modules/**/*
    - bin/**/*
    - db/**/*
    - config/**/*
Metrics/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false