AllCops:
  Excludes:
    - node_modules/**/*
    - bin/**/*
    - db/**/*
    - config/**/*
Metrics/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Max: 50
Metrics/MethodLength:
  Max: 20
